services:
  - type: web
    name: mern-estate
    env: node
    buildCommand: cd client && npm install && npm run build && cd ../api && npm install
    startCommand: cd api && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 